import { getStrokeCount } from './hanziData.ts'
import type { StrokeCharacter, StrokeCourse, StrokeDeck } from './types.ts'

export const COURSES: StrokeCourse[] = [
  {
    id: 'essentials',
    name: 'Essentials',
    description: 'Starter characters for building confident stroke order habits.',
    deckIds: ['numbers', 'common'],
  },
  {
    id: 'foundations',
    name: 'Foundations',
    description: 'Core pronouns, family terms, and everyday direction words.',
    deckIds: ['pronouns', 'family', 'colors-directions', 'adverbs'],
  },
  {
    id: 'daily-life',
    name: 'Daily Life',
    description: 'Common actions, food vocabulary, and natural elements.',
    deckIds: ['action-verbs', 'food-drink', 'nature-weather'],
  },
]

export const DECKS: StrokeDeck[] = [
  {
    id: 'numbers',
    courseId: 'essentials',
    name: 'Numbers',
    description: 'The ten numeric characters that show core stroke directions.',
    characterIds: ['一', '二', '三', '四', '五', '六', '七', '八', '九', '十'],
  },
  {
    id: 'common',
    courseId: 'essentials',
    name: 'Common',
    description: 'High-frequency building blocks for early reading and writing.',
    characterIds: ['人', '口', '日', '月', '水', '火', '山', '木', '大', '小'],
  },
  {
    id: 'pronouns',
    courseId: 'foundations',
    name: 'Pronouns',
    description: 'Personal pronouns and the plural suffix.',
    characterIds: ['我', '你', '您', '他', '她', '它', '们'],
  },
  {
    id: 'family',
    courseId: 'foundations',
    name: 'Family & People',
    description: 'Relatives and familial terms for everyday conversation.',
    characterIds: ['子', '女', '爸', '妈', '哥', '姐', '弟', '妹', '爷', '奶'],
  },
  {
    id: 'colors-directions',
    courseId: 'foundations',
    name: 'Colors & Directions',
    description: 'Basic color adjectives and spatial orientation words.',
    characterIds: ['白', '黑', '红', '黄', '蓝', '绿', '上', '下', '左', '右'],
  },
  {
    id: 'adverbs',
    courseId: 'foundations',
    name: 'Adverbs & Particles',
    description: 'High-frequency adverbs and grammatical particles for sentence building.',
    characterIds: ['很', '也', '都', '不', '吗', '呢', '吧'],
  },
  {
    id: 'action-verbs',
    courseId: 'daily-life',
    name: 'Action Verbs',
    description: 'Everyday action words for eating, moving, and communicating.',
    characterIds: ['吃', '喝', '走', '坐', '看', '听', '说', '学', '写', '立'],
  },
  {
    id: 'food-drink',
    courseId: 'daily-life',
    name: 'Food & Drink',
    description: 'Common ingredients, dishes, and beverages.',
    characterIds: ['米', '面', '菜', '果', '茶', '酒', '肉', '蛋', '鱼', '牛'],
  },
  {
    id: 'nature-weather',
    courseId: 'daily-life',
    name: 'Nature & Weather',
    description: 'Natural elements, weather phenomena, and the outdoors.',
    characterIds: ['天', '地', '风', '云', '雨', '花', '草', '土', '石', '金'],
  },
]

const CHARACTER_DETAILS: Omit<StrokeCharacter, 'strokeCount'>[] = [
  {
    character: '一',
    deckIds: ['numbers'],
    pinyin: 'yi1',
    pinyinMarked: 'yī',
    meaning: 'one',
    radical: '一',
    example: '一个人 - one person',
  },
  {
    character: '二',
    deckIds: ['numbers'],
    pinyin: 'er4',
    pinyinMarked: 'èr',
    meaning: 'two',
    radical: '二',
    example: '二月 - February',
  },
  {
    character: '三',
    deckIds: ['numbers'],
    pinyin: 'san1',
    pinyinMarked: 'sān',
    meaning: 'three',
    radical: '一',
    example: '三天 - three days',
  },
  {
    character: '四',
    deckIds: ['numbers'],
    pinyin: 'si4',
    pinyinMarked: 'sì',
    meaning: 'four',
    radical: '囗',
    example: '四口人 - four people',
  },
  {
    character: '五',
    deckIds: ['numbers'],
    pinyin: 'wu3',
    pinyinMarked: 'wǔ',
    meaning: 'five',
    radical: '二',
    example: '五月 - May',
  },
  {
    character: '六',
    deckIds: ['numbers'],
    pinyin: 'liu4',
    pinyinMarked: 'liù',
    meaning: 'six',
    radical: '八',
    example: '六个 - six items',
  },
  {
    character: '七',
    deckIds: ['numbers'],
    pinyin: 'qi1',
    pinyinMarked: 'qī',
    meaning: 'seven',
    radical: '一',
    example: '七天 - seven days',
  },
  {
    character: '八',
    deckIds: ['numbers'],
    pinyin: 'ba1',
    pinyinMarked: 'bā',
    meaning: 'eight',
    radical: '八',
    example: '八月 - August',
  },
  {
    character: '九',
    deckIds: ['numbers'],
    pinyin: 'jiu3',
    pinyinMarked: 'jiǔ',
    meaning: 'nine',
    radical: '乙',
    example: '九点 - nine o’clock',
  },
  {
    character: '十',
    deckIds: ['numbers'],
    pinyin: 'shi2',
    pinyinMarked: 'shí',
    meaning: 'ten',
    radical: '十',
    example: '十月 - October',
  },
  {
    character: '人',
    deckIds: ['common'],
    pinyin: 'ren2',
    pinyinMarked: 'rén',
    meaning: 'person',
    radical: '人',
    example: '人们 - people',
  },
  {
    character: '口',
    deckIds: ['common'],
    pinyin: 'kou3',
    pinyinMarked: 'kǒu',
    meaning: 'mouth',
    radical: '口',
    example: '人口 - population',
  },
  {
    character: '日',
    deckIds: ['common'],
    pinyin: 'ri4',
    pinyinMarked: 'rì',
    meaning: 'sun; day',
    radical: '日',
    example: '日子 - days',
  },
  {
    character: '月',
    deckIds: ['common'],
    pinyin: 'yue4',
    pinyinMarked: 'yuè',
    meaning: 'moon; month',
    radical: '月',
    example: '月亮 - moon',
  },
  {
    character: '水',
    deckIds: ['common'],
    pinyin: 'shui3',
    pinyinMarked: 'shuǐ',
    meaning: 'water',
    radical: '水',
    example: '喝水 - drink water',
  },
  {
    character: '火',
    deckIds: ['common'],
    pinyin: 'huo3',
    pinyinMarked: 'huǒ',
    meaning: 'fire',
    radical: '火',
    example: '火山 - volcano',
  },
  {
    character: '山',
    deckIds: ['common'],
    pinyin: 'shan1',
    pinyinMarked: 'shān',
    meaning: 'mountain',
    radical: '山',
    example: '山水 - landscape',
  },
  {
    character: '木',
    deckIds: ['common'],
    pinyin: 'mu4',
    pinyinMarked: 'mù',
    meaning: 'wood; tree',
    radical: '木',
    example: '木头 - wood',
  },
  {
    character: '大',
    deckIds: ['common'],
    pinyin: 'da4',
    pinyinMarked: 'dà',
    meaning: 'big',
    radical: '大',
    example: '大学 - university',
  },
  {
    character: '小',
    deckIds: ['common'],
    pinyin: 'xiao3',
    pinyinMarked: 'xiǎo',
    meaning: 'small',
    radical: '小',
    example: '小心 - careful',
  },

  /* Pronouns */
  {
    character: '我',
    deckIds: ['pronouns'],
    pinyin: 'wo3',
    pinyinMarked: 'wǒ',
    meaning: 'I; me',
    radical: '戈',
    example: '我们 - we',
  },
  {
    character: '你',
    deckIds: ['pronouns'],
    pinyin: 'ni3',
    pinyinMarked: 'nǐ',
    meaning: 'you',
    radical: '亻',
    example: '你好 - hello',
  },
  {
    character: '您',
    deckIds: ['pronouns'],
    pinyin: 'nin2',
    pinyinMarked: 'nín',
    meaning: 'you (formal)',
    radical: '心',
    example: '您好 - hello (formal)',
  },
  {
    character: '他',
    deckIds: ['pronouns'],
    pinyin: 'ta1',
    pinyinMarked: 'tā',
    meaning: 'he; him',
    radical: '亻',
    example: '他们 - they',
  },
  {
    character: '她',
    deckIds: ['pronouns'],
    pinyin: 'ta1',
    pinyinMarked: 'tā',
    meaning: 'she; her',
    radical: '女',
    example: '她们 - they (female)',
  },
  {
    character: '它',
    deckIds: ['pronouns'],
    pinyin: 'ta1',
    pinyinMarked: 'tā',
    meaning: 'it',
    radical: '宀',
    example: '它们 - they (objects)',
  },
  {
    character: '们',
    deckIds: ['pronouns', 'family'],
    pinyin: 'men5',
    pinyinMarked: 'men',
    meaning: 'plural suffix',
    radical: '亻',
    example: '我们 - we',
  },

  /* Family & People */
  {
    character: '子',
    deckIds: ['family'],
    pinyin: 'zi3',
    pinyinMarked: 'zǐ',
    meaning: 'child',
    radical: '子',
    example: '儿子 - son',
  },
  {
    character: '女',
    deckIds: ['family'],
    pinyin: 'nv3',
    pinyinMarked: 'nǚ',
    meaning: 'woman; female',
    radical: '女',
    example: '女儿 - daughter',
  },
  {
    character: '爸',
    deckIds: ['family'],
    pinyin: 'ba4',
    pinyinMarked: 'bà',
    meaning: 'dad',
    radical: '父',
    example: '爸爸 - dad',
  },
  {
    character: '妈',
    deckIds: ['family'],
    pinyin: 'ma1',
    pinyinMarked: 'mā',
    meaning: 'mom',
    radical: '女',
    example: '妈妈 - mom',
  },
  {
    character: '哥',
    deckIds: ['family'],
    pinyin: 'ge1',
    pinyinMarked: 'gē',
    meaning: 'older brother',
    radical: '口',
    example: '哥哥 - older brother',
  },
  {
    character: '姐',
    deckIds: ['family'],
    pinyin: 'jie3',
    pinyinMarked: 'jiě',
    meaning: 'older sister',
    radical: '女',
    example: '姐姐 - older sister',
  },
  {
    character: '弟',
    deckIds: ['family'],
    pinyin: 'di4',
    pinyinMarked: 'dì',
    meaning: 'younger brother',
    radical: '弓',
    example: '弟弟 - younger brother',
  },
  {
    character: '妹',
    deckIds: ['family'],
    pinyin: 'mei4',
    pinyinMarked: 'mèi',
    meaning: 'younger sister',
    radical: '女',
    example: '妹妹 - younger sister',
  },
  {
    character: '爷',
    deckIds: ['family'],
    pinyin: 'ye2',
    pinyinMarked: 'yé',
    meaning: 'grandpa',
    radical: '父',
    example: '爷爷 - grandpa',
  },
  {
    character: '奶',
    deckIds: ['family'],
    pinyin: 'nai3',
    pinyinMarked: 'nǎi',
    meaning: 'grandma',
    radical: '女',
    example: '奶奶 - grandma',
  },

  /* Colors & Directions */
  {
    character: '白',
    deckIds: ['colors-directions'],
    pinyin: 'bai2',
    pinyinMarked: 'bái',
    meaning: 'white',
    radical: '白',
    example: '白天 - daytime',
  },
  {
    character: '黑',
    deckIds: ['colors-directions'],
    pinyin: 'hei1',
    pinyinMarked: 'hēi',
    meaning: 'black',
    radical: '黑',
    example: '黑色 - black',
  },
  {
    character: '红',
    deckIds: ['colors-directions'],
    pinyin: 'hong2',
    pinyinMarked: 'hóng',
    meaning: 'red',
    radical: '纟',
    example: '红色 - red',
  },
  {
    character: '黄',
    deckIds: ['colors-directions'],
    pinyin: 'huang2',
    pinyinMarked: 'huáng',
    meaning: 'yellow',
    radical: '黄',
    example: '黄色 - yellow',
  },
  {
    character: '蓝',
    deckIds: ['colors-directions'],
    pinyin: 'lan2',
    pinyinMarked: 'lán',
    meaning: 'blue',
    radical: '艹',
    example: '蓝色 - blue',
  },
  {
    character: '绿',
    deckIds: ['colors-directions'],
    pinyin: 'lv4',
    pinyinMarked: 'lǜ',
    meaning: 'green',
    radical: '纟',
    example: '绿色 - green',
  },
  {
    character: '上',
    deckIds: ['colors-directions'],
    pinyin: 'shang4',
    pinyinMarked: 'shàng',
    meaning: 'up; above',
    radical: '一',
    example: '上午 - morning',
  },
  {
    character: '下',
    deckIds: ['colors-directions'],
    pinyin: 'xia4',
    pinyinMarked: 'xià',
    meaning: 'down; below',
    radical: '一',
    example: '下午 - afternoon',
  },
  {
    character: '左',
    deckIds: ['colors-directions'],
    pinyin: 'zuo3',
    pinyinMarked: 'zuǒ',
    meaning: 'left',
    radical: '工',
    example: '左右 - left and right',
  },
  {
    character: '右',
    deckIds: ['colors-directions'],
    pinyin: 'you4',
    pinyinMarked: 'yòu',
    meaning: 'right',
    radical: '口',
    example: '右手 - right hand',
  },

  /* Adverbs & Particles */
  {
    character: '很',
    deckIds: ['adverbs'],
    pinyin: 'hen3',
    pinyinMarked: 'hěn',
    meaning: 'very',
    radical: '彳',
    example: '很好 - very good',
  },
  {
    character: '也',
    deckIds: ['adverbs'],
    pinyin: 'ye3',
    pinyinMarked: 'yě',
    meaning: 'also',
    radical: '乙',
    example: '我也是 - me too',
  },
  {
    character: '都',
    deckIds: ['adverbs'],
    pinyin: 'dou1',
    pinyinMarked: 'dōu',
    meaning: 'all; both',
    radical: '阝',
    example: '大家都好 - everyone is fine',
  },
  {
    character: '不',
    deckIds: ['adverbs'],
    pinyin: 'bu4',
    pinyinMarked: 'bù',
    meaning: 'not',
    radical: '一',
    example: '不是 - is not',
  },
  {
    character: '吗',
    deckIds: ['adverbs'],
    pinyin: 'ma5',
    pinyinMarked: 'ma',
    meaning: 'question particle',
    radical: '口',
    example: '好吗？- OK?',
  },
  {
    character: '呢',
    deckIds: ['adverbs'],
    pinyin: 'ne5',
    pinyinMarked: 'ne',
    meaning: 'question particle (contextual)',
    radical: '口',
    example: '你呢？- And you?',
  },
  {
    character: '吧',
    deckIds: ['adverbs'],
    pinyin: 'ba5',
    pinyinMarked: 'ba',
    meaning: 'suggestion particle',
    radical: '口',
    example: '走吧 - let\'s go',
  },

  /* Action Verbs */
  {
    character: '吃',
    deckIds: ['action-verbs'],
    pinyin: 'chi1',
    pinyinMarked: 'chī',
    meaning: 'to eat',
    radical: '口',
    example: '吃饭 - eat a meal',
  },
  {
    character: '喝',
    deckIds: ['action-verbs'],
    pinyin: 'he1',
    pinyinMarked: 'hē',
    meaning: 'to drink',
    radical: '口',
    example: '喝水 - drink water',
  },
  {
    character: '走',
    deckIds: ['action-verbs'],
    pinyin: 'zou3',
    pinyinMarked: 'zǒu',
    meaning: 'to walk',
    radical: '走',
    example: '走路 - walk',
  },
  {
    character: '坐',
    deckIds: ['action-verbs'],
    pinyin: 'zuo4',
    pinyinMarked: 'zuò',
    meaning: 'to sit',
    radical: '土',
    example: '坐下 - sit down',
  },
  {
    character: '看',
    deckIds: ['action-verbs'],
    pinyin: 'kan4',
    pinyinMarked: 'kàn',
    meaning: 'to look; to read',
    radical: '目',
    example: '看书 - read a book',
  },
  {
    character: '听',
    deckIds: ['action-verbs'],
    pinyin: 'ting1',
    pinyinMarked: 'tīng',
    meaning: 'to listen',
    radical: '口',
    example: '听音乐 - listen to music',
  },
  {
    character: '说',
    deckIds: ['action-verbs'],
    pinyin: 'shuo1',
    pinyinMarked: 'shuō',
    meaning: 'to speak',
    radical: '讠',
    example: '说话 - speak',
  },
  {
    character: '学',
    deckIds: ['action-verbs'],
    pinyin: 'xue2',
    pinyinMarked: 'xué',
    meaning: 'to learn',
    radical: '子',
    example: '学习 - study',
  },
  {
    character: '写',
    deckIds: ['action-verbs'],
    pinyin: 'xie3',
    pinyinMarked: 'xiě',
    meaning: 'to write',
    radical: '冖',
    example: '写字 - write characters',
  },
  {
    character: '立',
    deckIds: ['action-verbs'],
    pinyin: 'li4',
    pinyinMarked: 'lì',
    meaning: 'to stand',
    radical: '立',
    example: '站立 - stand',
  },

  /* Food & Drink */
  {
    character: '米',
    deckIds: ['food-drink'],
    pinyin: 'mi3',
    pinyinMarked: 'mǐ',
    meaning: 'rice',
    radical: '米',
    example: '米饭 - cooked rice',
  },
  {
    character: '面',
    deckIds: ['food-drink'],
    pinyin: 'mian4',
    pinyinMarked: 'miàn',
    meaning: 'face; noodles',
    radical: '面',
    example: '面包 - bread',
  },
  {
    character: '菜',
    deckIds: ['food-drink'],
    pinyin: 'cai4',
    pinyinMarked: 'cài',
    meaning: 'vegetable; dish',
    radical: '艹',
    example: '菜单 - menu',
  },
  {
    character: '果',
    deckIds: ['food-drink'],
    pinyin: 'guo3',
    pinyinMarked: 'guǒ',
    meaning: 'fruit',
    radical: '木',
    example: '水果 - fruit',
  },
  {
    character: '茶',
    deckIds: ['food-drink'],
    pinyin: 'cha2',
    pinyinMarked: 'chá',
    meaning: 'tea',
    radical: '艹',
    example: '喝茶 - drink tea',
  },
  {
    character: '酒',
    deckIds: ['food-drink'],
    pinyin: 'jiu3',
    pinyinMarked: 'jiǔ',
    meaning: 'alcohol',
    radical: '酉',
    example: '喝酒 - drink alcohol',
  },
  {
    character: '肉',
    deckIds: ['food-drink'],
    pinyin: 'rou4',
    pinyinMarked: 'ròu',
    meaning: 'meat',
    radical: '肉',
    example: '牛肉 - beef',
  },
  {
    character: '蛋',
    deckIds: ['food-drink'],
    pinyin: 'dan4',
    pinyinMarked: 'dàn',
    meaning: 'egg',
    radical: '虫',
    example: '鸡蛋 - egg',
  },
  {
    character: '鱼',
    deckIds: ['food-drink'],
    pinyin: 'yu2',
    pinyinMarked: 'yú',
    meaning: 'fish',
    radical: '鱼',
    example: '吃鱼 - eat fish',
  },
  {
    character: '牛',
    deckIds: ['food-drink'],
    pinyin: 'niu2',
    pinyinMarked: 'niú',
    meaning: 'cow',
    radical: '牛',
    example: '牛奶 - milk',
  },

  /* Nature & Weather */
  {
    character: '天',
    deckIds: ['nature-weather'],
    pinyin: 'tian1',
    pinyinMarked: 'tiān',
    meaning: 'sky; day',
    radical: '大',
    example: '今天 - today',
  },
  {
    character: '地',
    deckIds: ['nature-weather'],
    pinyin: 'di4',
    pinyinMarked: 'dì',
    meaning: 'earth; ground',
    radical: '土',
    example: '地方 - place',
  },
  {
    character: '风',
    deckIds: ['nature-weather'],
    pinyin: 'feng1',
    pinyinMarked: 'fēng',
    meaning: 'wind',
    radical: '风',
    example: '大风 - strong wind',
  },
  {
    character: '云',
    deckIds: ['nature-weather'],
    pinyin: 'yun2',
    pinyinMarked: 'yún',
    meaning: 'cloud',
    radical: '二',
    example: '白云 - white cloud',
  },
  {
    character: '雨',
    deckIds: ['nature-weather'],
    pinyin: 'yu3',
    pinyinMarked: 'yǔ',
    meaning: 'rain',
    radical: '雨',
    example: '下雨 - rain',
  },
  {
    character: '花',
    deckIds: ['nature-weather'],
    pinyin: 'hua1',
    pinyinMarked: 'huā',
    meaning: 'flower',
    radical: '艹',
    example: '花园 - garden',
  },
  {
    character: '草',
    deckIds: ['nature-weather'],
    pinyin: 'cao3',
    pinyinMarked: 'cǎo',
    meaning: 'grass',
    radical: '艹',
    example: '草地 - lawn',
  },
  {
    character: '土',
    deckIds: ['nature-weather'],
    pinyin: 'tu3',
    pinyinMarked: 'tǔ',
    meaning: 'earth; soil',
    radical: '土',
    example: '土地 - land',
  },
  {
    character: '石',
    deckIds: ['nature-weather'],
    pinyin: 'shi2',
    pinyinMarked: 'shí',
    meaning: 'stone',
    radical: '石',
    example: '石头 - stone',
  },
  {
    character: '金',
    deckIds: ['nature-weather'],
    pinyin: 'jin1',
    pinyinMarked: 'jīn',
    meaning: 'gold; metal',
    radical: '金',
    example: '金色 - golden',
  },
]

export const CHARACTERS: StrokeCharacter[] = CHARACTER_DETAILS.map((entry) => ({
  ...entry,
  strokeCount: getStrokeCount(entry.character),
}))

export function getDeck(deckId: string): StrokeDeck | undefined {
  return DECKS.find((deck) => deck.id === deckId)
}

export function getCharacter(character: string): StrokeCharacter | undefined {
  return CHARACTERS.find((entry) => entry.character === character)
}

export function getDeckCharacters(deckId: string): StrokeCharacter[] {
  const deck = getDeck(deckId)
  if (!deck) return []
  return deck.characterIds
    .map((character) => getCharacter(character))
    .filter((entry): entry is StrokeCharacter => Boolean(entry))
}
